#!/bin/bash

USER_ID=${LOCAL_USER_ID:-9001}
GROUP_ID=${LOCAL_GROUP_ID:-9001}
PATH=$PATH:/usr/local/dotnet/tools

# Create user with matching group, but only if it doesn't exist yet
id user > /dev/null 2>&1 || groupadd -g $GROUP_ID user
id user > /dev/null 2>&1 || useradd --shell /bin/bash -u $USER_ID -g $GROUP_ID -o -c "" -m user
export HOME=/home/user

exec gosu user /bin/bash -c "$*"
