#!/bin/bash

if [ "$ENVIRONMENT" = DEVELOPMENT ]; then 
    ENV=DEVELOPMENT
    ENV_FILE=./env/.env.dev
else
    ENV=PRODUCTION
    ENV_FILE=./env/.env
fi

set -a
source $ENV_FILE
set +a

COMMAND="$1"
COMMAND_ARGUMENTS="${@:2}"
DOCKER_ARGUMENTS="-p $PROJECT_NAME -f ./docker-compose.yml"

if [ "$ENV" = DEVELOPMENT ]; then
    DOCKER_ARGUMENTS+="${ARGUMENTS} -f ./docker-compose.dev.yml"
else
    COMMAND_ARGUMENTS+=" --no-build"
fi

echo "Running $ENV environment"

ENV_FILE=$ENV_FILE          \
docker                      \
    compose                 \
    $DOCKER_ARGUMENTS       \
    $COMMAND                \
    $COMMAND_ARGUMENTS      \
