version: '3.9'

services:
  caddy:
    image: ${DOCKER_REGISTRY}/agile-project/caddy:${ENV}
    pull_policy: always
    restart: 'unless-stopped'
    ports:
      - ${APP_PORT}:80
  backend:
    image: ${DOCKER_REGISTRY}/agile-project/backend:${ENV}
    pull_policy: always
    restart: 'unless-stopped'
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./backend/AgileApp/ESD/
        target: /app/ESD/
        bind:
          propagation: "rslave"
    env_file:
      - ${ENV_FILE}
      - ${ENV_FILE_OVERRIDE}
  db:
    image: postgres:15-alpine
    pull_policy: always
    restart: 'unless-stopped'
    env_file:
      - ${ENV_FILE}
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
      - type: bind
        source: ./docker/db/migrations/
        target: /docker-entrypoint-initdb.d/
        bind:
          propagation: "rslave"