version: '3.9'

services:
  nginx:
    image: ghcr.io/blayeer/agile-project/nginx:latest
    restart: 'unless-stopped'
    ports:
      - 80:80
  backend:
    image: ghcr.io/blayeer/agile-project/backend:latest
    restart: 'unless-stopped'
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./backend/AgileApp/ESD/
        target: /app/ESD/
        bind:
          propagation: "rslave"
    env_file:
      - ${ENV_FILE}
  db:
    image: postgres:15-alpine
    restart: 'unless-stopped'
    env_file:
      - ${ENV_FILE}
  