version: '3.9'

services:
  frontend:
    image: ghcr.io/blayeer/agile-project/frontend:latest
    restart: 'unless-stopped'
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./frontend/agile4all:/usr/app
      - ./frontend/agile4all/node_modules:/usr/app/node_modules
    entrypoint: npm run start
    env_file:
      - ${ENV_FILE}
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - 4200:4200
  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./backend:/backend
      - ./docker/backend/setup.dev.sh:/setup.sh
      - ~/.nuget/packages:/root/.nuget/packages:rw
    entrypoint: /bin/bash -c "/setup.sh && dotnet watch run --urls http://0.0.0.0:8000 --project /backend/AgileApp"