version: '3.9'

services:
  frontend:
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./frontend/agile4all:/usr/app
      - ./frontend/agile4all/node_modules:/usr/app/node_modules
    entrypoint: /bin/bash -c "npm install && npm run start"
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - 4200:80
    depends_on:
      - frontend
  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./backend:/backend
      - ./docker/backend/entrypoint.sh:/entrypoint.sh
      - ./docker/backend/entrypoint.dev.sh:/entrypoint.dev.sh
      - ~/.nuget/packages:/root/.nuget/packages:rw
      - ./docker/db/migrations:/migrations
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID:-9001}
      - LOCAL_GROUP_ID=${LOCAL_GROUP_ID:-9001}
    entrypoint: /entrypoint.dev.sh "dotnet watch run --urls 'http://0.0.0.0:8000;http://0.0.0.0:9000' --project /backend/AgileApp"