version: '3.9'

services:
  frontend:
    image: blayer.mooo.com:5000/agile-project/frontend:latest
    restart: 'unless-stopped'
    env_file:
      - ${ENV_FILE}
  nginx:
    image: blayer.mooo.com:5000/agile-project/nginx:latest
    restart: 'unless-stopped'
    ports:
      - 5700:80
  backend:
    image: blayer.mooo.com:5000/agile-project/backend:latest
    restart: 'unless-stopped'
    depends_on:
      - db
    volumes:
      - type: bind
        source: ./backend/AgileApp/ESD/
        target: /app/ESD/
        bind:
          propagation: "rslave"
    env_file:
      - ${ENV_FILE}
  db:
    image: postgres:15-alpine
    restart: 'unless-stopped'
    env_file:
      - ${ENV_FILE}
    volumes:
      - type: bind
        source: ./docker/db/migrations/
        target: /docker-entrypoint-initdb.d/
        bind:
          propagation: "rslave"