version: '3.9'

services:
  frontend:
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile.${ENV}
    volumes:
      - ./frontend/agile4all:/frontend/agile4all
      - ./frontend/agile4all/node_modules:/frontend/agile4all/node_modules
  nginx:
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile.${ENV}
    ports:
      - 4200:80
    depends_on:
      - frontend
    volumes:
      - ./docker/nginx/nginx.dev.conf:/etc/nginx/nginx.conf
  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile.${ENV}
    volumes:
      - ./backend:/backend
      - ./docker/db/migrations:/migrations
    environment:
      - LOCAL_USER_ID=${LOCAL_USER_ID:-9001}
      - LOCAL_GROUP_ID=${LOCAL_GROUP_ID:-9001}
  db:
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: