#!/bin/bash

if [ "$ENVIRONMENT" = DEVELOPMENT ]; then 
    ENV=DEVELOPMENT
    ENV_FILE=./env/.env.dev
else
    ENV=PRODUCTION
    ENV_FILE=./env/.env
fi

set -a
source $ENV_FILE
set +a

UP_ARGUMENTS="$@"
ARGUMENTS="-p $PROJECT_NAME -f ./docker-compose.yml"

if [ "$ENV" = DEVELOPMENT ]; then
    ARGUMENTS="${ARGUMENTS} -f ./docker-compose.dev.yml"
else
    UP_ARGUMENTS+=" --no-build"
fi

echo "Running $ENV environment"

docker                      \
    compose                 \
    $ARGUMENTS              \
    up                      \
    $UP_ARGUMENTS           \
