FROM node:18-bullseye-slim as frontend

WORKDIR /usr/app
COPY frontend/agile4all/ /usr/app

RUN npm ci
RUN npm run build

FROM nginx:alpine

EXPOSE 80

COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=frontend /usr/app/build /usr/share/nginx/html
